/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
 /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
 */
 tutorialSidebar: [
      {
        type: 'category',
        label: 'Getting Started',
        items: [
          {
            type: 'doc',
            id: 'intro', // document ID
            label: 'Introduction', // sidebar label
          },
          {
            type: 'doc',
            id: 'technicalarchitecture-mentored', // document ID
            label: 'Architecture', // sidebar label
          },
          {
            type: 'doc',
            id: 'key-capabilities', // document ID
            label: 'Key Capabilities', // sidebar label
          },
        ]
      },
      {
        type: 'category',
        label: 'Hosting and Customizing Your Instance',
        items: [
          {
            type: 'doc',
            id: 'settingup-overview', // document ID
            label: 'Overview', // sidebar label
          },
          {
            type: 'category',
            label: 'Setting up the Microservices',
            items: [
              {
                  type: 'doc',
                  id: 'settingup-userservice', // document ID
                  label: 'Setting up the User Service', // sidebar label
              },
              {
                  type: 'doc',
                  id: 'settingup-mentoringservice', // document ID
                  label: 'Setting up the Mentoring Service', // sidebar label
              },
              {
                  type: 'doc',
                  id: 'settingup-notificationsservice', // document ID
                  label: 'Setting up the Notifications Service', // sidebar label
              },
              {
                  type: 'doc',
                  id: 'settingup-schedulerservice', // document ID
                  label: 'Setting up the Scheduler Service', // sidebar label
              },
              {
                  type: 'doc',
                  id: 'settingup-bbb', // document ID
                  label: 'Setting up the BigBlueButton Service', // sidebar label
              },
            ]
          },
        ]
      },                
      {
        type: 'doc',
        id: 'settingup-mentoredapplication', // document ID
        label: 'Customizing the Mobile Application', // sidebar label
      },
      {
        type: 'doc',
        id: 'settingup-webportal', // document ID
        label: 'Customizing the Web Portal', // sidebar label
      },
      {
        type: 'category',
        label: 'Using the Application',
        items: [
          {
            type: 'doc',
            id: 'using-the-mentored-application', // document ID
            label: 'About the Application', // sidebar label
          },
          {
            type: 'doc',
            id: 'notifications', // document ID
            label: 'Notifications', // sidebar label
          },


          {
            type: 'category',
            label: 'How Mentors Can Use the Application',
            items: [
              
                {
                  type: 'doc',
                  id: 'signing-up-as-a-mentor', // document ID
                  label: 'Signing up as a Mentor', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'logging-in', // document ID
                  label: 'Logging in', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'change-language', // document ID
                  label: 'Changing the Language Settings', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'report-an-issue', // document ID
                  label: 'Reporting an Issue', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'using-faq', // document ID
                  label: 'Using the FAQ Page', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'view-helpvideos', // document ID
                  label: 'Viewing the Help Videos', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'creating-and-managing-mentor-profile', // document ID
                  label: 'Creating and Managing a Profile', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'mentor-directory', // document ID
                  label: 'Using the Mentor Directory', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'viewmentorprofilelink', // document ID
                  label: 'Using a Shared Link to View a Mentor Profile', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'setting-up-a-mentored-session', // document ID
                  label: 'Setting up a Session', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'inviting-mentorsandmentees-host', // document ID
                  label: 'Inviting Mentors and Mentees', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'starting-a-session', // document ID
                  label: 'Starting a Session', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'dashboard-for-mentors', // document ID
                  label: 'Dashboard', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'feedbackformentors', // document ID
                  label: 'Providing Feedback on a Session', // sidebar label
                }
            ]
          },

          {
            type: 'category',
            label: 'How Mentees Can Use the Application',
            items: [
               
                {
                  type: 'doc',
                  id: 'signing-up-as-a-mentee', // document ID
                  label: 'Signing up as a Mentee', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'logging-in', // document ID
                  label: 'Logging in', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'change-language', // document ID
                  label: 'Changing the Language Settings', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'report-an-issue', // document ID
                  label: 'Reporting an Issue', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'using-faq', // document ID
                  label: 'Using the FAQ Page', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'view-helpvideos', // document ID
                  label: 'Viewing the Help Videos', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'creating-and-managing-mentee-profile', // document ID
                  label: 'Creating and Managing a Profile', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'mentor-directory', // document ID
                  label: 'Using the Mentor Directory', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'viewmentorprofilelink', // document ID
                  label: 'Using a Shared Link to View a Mentor Profile', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'enrolling-for-a-session', // document ID
                  label: 'Enrolling for a  Session', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'inviting-mentorsandmentees-participants', // document ID
                  label: 'Inviting Mentors and Mentees', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'joining-a-session', // document ID
                  label: 'Joining a Session', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'joining-sessions-using-a-shared-link', // document ID
                  label: 'Using a Shared Link to Join a Session', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'dashboard-for-mentees', // document ID
                  label: 'Dashboard', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'feedbackformentees', // document ID
                  label: 'Providing Feedback on a Session', // sidebar label
                }
              ]
            },
          ]
      },
      {
        type: 'category',
        label: 'Additional Technical Resources',
        items: [
          {
            type: 'doc',
            id: 'apidocumentation', // document ID
            label: 'API Documentation', // sidebar label
          },
          {
            type: 'doc',
            id: 'databasedesign', // document ID
            label: 'Database Design', // sidebar label
          },
          {
            type: 'doc',
            id: 'mentoredrepos', // document ID
            label: 'Source Code Repositories', // sidebar label
          },
        ]
      },
      {
        type: 'doc',
        id: 'faq', // document ID
        label: 'FAQs', // sidebar label
      },
    ]
  };
module.exports = sidebars;